In [15]:
import numpy as np
ar = np.array([[1,2,3],[4,5,6]])
ar
ar.shape

(2, 3)

In [3]:
ar = np.array([[1, 2, 3], [4, 5, 6]])
ar.shape

(2, 3)

In [24]:
mat = np.arange(0, 100, 5).reshape(2, 10)
mat

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [50, 55, 60, 65, 70, 75, 80, 85, 90, 95]])

In [11]:
e = np.array([25, 50, 4, 5, 70, 20])
np.max(e)
np.min(e)
e.itemsize
np.sum(e)

4

In [27]:
r = np.ones(50).reshape(5, 10)
r

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [30]:
s = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
np.random.shuffle(s)
s

array([[ 7,  8,  9],
       [ 4,  5,  6],
       [10, 11, 12],
       [ 1,  2,  3]])

In [35]:
a = [1, 2, 3, 4, 5]
c = "hello"
type(a)
b = np.array(c)
type(b)
b

array('hello', dtype='<U5')